### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/KCET#35]
We should clean up the files before we make this repo open.

Do we still need

- [x] drug_kinase_links_3_2021.csv

Look at the other files in the input directory as well

**Comment by pnrobinson** [comment]
We should update the README file to indicate that this repository is related to the manuscript. Is it correct that the notebooks related to the manuscript are all on the subdirectories, and the other notebooks are exploratory? If that is the case, then let's make a new subdirectory called data_exploration and put the notebooks there, they might be useful to someone.

**Comment by vidarmehr** [comment]
I created the subdirectory data_exploration and put the corresponding notebooks there.

**Comment by pnrobinson** [comment]
refactored -- Done!
